#!/usr/bin/env python3
"""装配 timeline.json —— 音频秒数 → 帧数。

用法：
    python3 build_timeline.py <集名> [--gap 1.6]

读：
    <集名>_video/narration/all.json     旁白文本（pNN -> 文本）
    <集名>_video/design.md             槽位坐标与文案
    audio/<集名>/pNN.wav               gen_tts.sh 的产物（实测时长）
写：
    remotion/public/<集名>/timeline.json
    remotion/public/<集名>/timeline.ts  （Remotion 直接 import 的模块）

页长口径：纯音频秒 + pageGap。这是终态帧抽帧的唯一权威来源
（METHODOLOGY §7：不要用 _meta.json 的 bounds）。
"""
import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE_GAP_DEFAULT = 1.6


def probe_seconds(path: Path) -> float:
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nw=1:nk=1", str(path)],
        capture_output=True, text=True, check=True)
    return round(float(r.stdout.strip()), 3)


def load_slots(design: Path) -> dict:
    """从 design.md 的 json 代码块抽槽位（结构同 E10）。

    不能用正则按行切：usage 字段里可能有 {} 或跨行。
    这里做字符串感知的括号配平——引号内的括号不计数。
    """
    text = design.read_text(encoding="utf-8")
    pages = {}
    for m in re.finditer(r'"(p\d{2})"\s*:\s*\[(.*?)\n\s*\]', text, re.S):
        page, body = m.group(1), m.group(2)
        slots = []
        depth = 0
        in_str = False
        esc = False
        buf = []
        for ch in body:
            if in_str:
                buf.append(ch)
                if esc:
                    esc = False
                elif ch == "\\":
                    esc = True
                elif ch == '"':
                    in_str = False
                continue
            if ch == '"':
                in_str = True
                buf.append(ch)
                continue
            if ch == "{":
                depth += 1
                if depth == 1:
                    buf = ["{"]
                    continue
            elif ch == "}":
                depth -= 1
                buf.append("}")
                if depth == 0:
                    slots.append(json.loads("".join(buf)))
                    continue
                continue
            if depth >= 1:
                buf.append(ch)
        pages[page] = slots
    return pages


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("series")
    ap.add_argument("--gap", type=float, default=PAGE_GAP_DEFAULT)
    ap.add_argument("--board-dir", default=None,
                    help="板面图目录（相对 public/），默认 boards/")
    args = ap.parse_args()

    series = args.series
    ep = ROOT / f"{series}_video"
    if not ep.is_dir():
        print(f"错误：找不到 {ep}", file=sys.stderr)
        return 1

    narr_path = ep / "narration" / "all.json"
    if not narr_path.is_file():
        print(f"错误：找不到 {narr_path}", file=sys.stderr)
        return 1
    narr = json.loads(narr_path.read_text(encoding="utf-8"))

    design = ep / "design.md"
    slots_by_page = load_slots(design) if design.is_file() else {}
    if not slots_by_page:
        print(f"警告：{design} 未解析出槽位，将装配无字探针片", file=sys.stderr)

    board_dir = args.board_dir or "boards"
    audio_root = ROOT / "audio" / series

    pages = []
    for pid in sorted(narr):
        wav = audio_root / f"{pid}.wav"
        if not wav.is_file():
            print(f"错误：缺音频 {wav}", file=sys.stderr)
            return 1
        secs = probe_seconds(wav)
        slots = slots_by_page.get(pid, [])
        for s in slots:
            # usage 即该槽位的成片文案；锚点缺省即页内首帧。
            s.setdefault("text", s.get("usage", ""))
        pages.append({
            "id": pid,
            "board": f"{board_dir}/{series}_{pid}.png",
            "audio": f"audio/{series}/{pid}.wav",
            "caption": narr[pid],
            "slots": slots,
            "audioSeconds": secs,
            "pageSeconds": round(secs + args.gap, 3),
        })

    timeline = {
        "fps": 30,
        "width": 1920,
        "height": 1080,
        "pageGap": args.gap,
        "pages": pages,
    }

    out_dir = ROOT / "remotion" / "public" / series
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "timeline.json").write_text(
        json.dumps(timeline, ensure_ascii=False, indent=1), encoding="utf-8")

    # Remotion 打包要求静态 import，所以每集生成一个入口：
    #   public/<集名>/timeline.ts  —— 数据模块
    #   src/series/<集名>.tsx       —— 入口，registerRoot
    # 板面图缺失时自动降级为探针片（纯白底），不占图像配额也能验完其余环节。
    (out_dir / "timeline.ts").write_text(
        "// GENERATED by scripts/build_timeline.py — do not edit by hand.\n"
        'import { Timeline } from "../../src/types";\n\n'
        f"export const timeline: Timeline = {json.dumps(timeline, ensure_ascii=False, indent=1)};\n",
        encoding="utf-8",
    )

    series_dir = ROOT / "remotion" / "src" / "series"
    series_dir.mkdir(parents=True, exist_ok=True)

    # Remotion 只能从 public/ 提供静态资源，而 gen_tts.sh 把音频写在 audio/<集名>/。
    # 这里做软链接，不复制 300KB+ 的 wav。
    public_audio = ROOT / "remotion" / "public" / "audio" / series
    public_audio.parent.mkdir(parents=True, exist_ok=True)
    if public_audio.is_symlink() or public_audio.exists():
        if public_audio.is_symlink():
            public_audio.unlink()
        else:
            shutil.rmtree(public_audio)
    public_audio.symlink_to(audio_root.resolve(), target_is_directory=True)

    public_boards = ROOT / "remotion" / "public" / board_dir
    public_boards.mkdir(parents=True, exist_ok=True)

    missing_boards = [
        p["id"] for p in pages
        if not (public_boards / f"{series}_{p['id']}.png").is_file()
    ]
    # Remotion 要求入口文件里字面出现 registerRoot（CLI 会静态扫这个字符串），
    # 所以不能藏在 ../series 的工厂函数里，只能内联展开。
    (series_dir / f"{series}.tsx").write_text(
        "// GENERATED by scripts/build_timeline.py — do not edit by hand.\n"
        'import React from "react";\n'
        'import { Composition, registerRoot } from "remotion";\n'
        'import { Lesson, totalFrames } from "../Lesson";\n'
        f'import {{ timeline }} from "../../public/{series}/timeline";\n\n'
        f'const placeholderBoard = {str(bool(missing_boards)).lower()};\n'
        "const Root: React.FC = () => (\n"
        "  <Composition\n"
        f'    id="{series}Course"\n'
        "    component={Lesson}\n"
        "    durationInFrames={Math.max(totalFrames(timeline, timeline.fps), 1)}\n"
        "    fps={timeline.fps}\n"
        "    width={timeline.width}\n"
        "    height={timeline.height}\n"
        "    defaultProps={{ timeline, placeholderBoard }}\n"
        "  />\n"
        ");\n\n"
        "registerRoot(Root);\n",
        encoding="utf-8",
    )

    total_audio = sum(p["audioSeconds"] for p in pages)
    total_page = sum(p["pageSeconds"] for p in pages)
    n_slots = sum(len(p["slots"]) for p in pages)
    print(f"集 {series}: {len(pages)} 页 / {n_slots} 槽位")
    print(f"  纯音频 {total_audio:.2f}s   含留白 {total_page:.2f}s   帧数 {round(total_page*30)}")
    print(f"  板面缺失 {len(missing_boards)}/{len(pages)} -> "
          f"{'探针片（白底）' if missing_boards else '正式板面'}")
    print(f"  -> {out_dir/'timeline.json'}")
    print(f"  渲染: npx remotion render src/series/{series}.tsx {series}Course out/{series}.mp4")
    return 0


if __name__ == "__main__":
    sys.exit(main())
