#!/usr/bin/env python3
"""把「黑板资源包」格式的 JSON 转成 Remotion timeline。

输入格式沿用 ontology_文本框定位_v2.3 的场景结构：
    scenes: [{ scene_id, image, audio, caption,
               boxes: [{box_id, text, rect_1920x1080_px{x,y,w,h},
                        font_size_1920x1080_px, color, align, background,
                        stage}],        # stage: 第几状态可见（1 起）
             }]
    stages_per_scene: 每场的状态数（可选，缺省取 boxes 的最大 stage）
    minimum_pause_seconds: 思考停顿（追加到该页时长）

输出：remotion/public/<集名>/timeline.json + timeline.ts + src/series/<集名>.tsx
槽位 anchor 按状态均匀分布在音频时长内（第 i 状态在 i/(n) 比例处进场）。

用法：
    python3 scripts/build_from_pack.py <集名> <pack.json>
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REMOTION = ROOT / "remotion"
PUBLIC = REMOTION / "public"
PAGE_GAP_DEFAULT = 1.6
FPS = 30


def ffprobe_seconds(path: Path) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nw=1:nk=1", str(path)],
        capture_output=True, text=True, check=True,
    )
    return float(out.stdout.strip())


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("series")
    ap.add_argument("pack", help="资源包场景 JSON 路径")
    ap.add_argument("--audio-dir", default=None,
                    help="音频目录（默认 audio/<集名>/）")
    ap.add_argument("--gap", type=float, default=PAGE_GAP_DEFAULT)
    args = ap.parse_args()

    series = args.series
    pack_path = Path(args.pack)
    pack = json.loads(pack_path.read_text(encoding="utf-8"))

    audio_dir = Path(args.audio_dir) if args.audio_dir else ROOT / "audio" / series
    board_dir = PUBLIC / "boards"

    pages = []
    for scene in pack["scenes"]:
        sid = scene["scene_id"]
        wav = audio_dir / f"{sid}.wav"
        if not wav.is_file():
            print(f"错误：缺音频 {wav}，先跑 gen_tts.sh", file=sys.stderr)
            return 1
        audio_sec = ffprobe_seconds(wav)

        board_rel = scene.get("image")  # 相对 public/ 的路径
        board_abs = PUBLIC / board_rel if board_rel else None
        has_board = board_abs and board_abs.is_file()
        if not has_board:
            print(f"警告：{sid} 板面缺失 {board_rel}，该页将用白底探针片")

        boxes = scene["boxes"]
        n_stages = max((b.get("stage", 1) for b in boxes), default=1)
        # 每个状态的进场帧：第 i 状态在音频的 i/n_stages 处
        for b in boxes:
            stage = b.get("stage", 1)
            b["anchor"] = round((stage - 1) / max(n_stages, 1) * audio_sec * FPS)

        pause = float(scene.get("pause_seconds", 0))
        page_sec = audio_sec + pause + args.gap
        pages.append({
            "id": sid,
            "board": board_rel or "",
            "audio": f"audio/{series}/{sid}.wav",
            "caption": scene.get("caption", ""),
            "slots": [
                {
                    "id": b["box_id"],
                    "x": r["x"], "y": r["y"], "w": r["w"], "h": r["h"],
                    "role": b.get("role", "body"),
                    "text": b["text"],
                    "anchor": b["anchor"],
                    "fontSize": b.get("font_size", 30),
                    "color": b.get("color"),
                    "align": b.get("align", "left"),
                    "noBacking": b.get("background") in (None, "transparent"),
                }
                for b, r in ((b, b["rect_1920x1080_px"]) for b in boxes)
            ],
            "audioSeconds": round(audio_sec + pause, 2),
            "pageSeconds": round(page_sec, 2),
        })

    timeline = {"fps": FPS, "width": 1920, "height": 1080,
                "pageGap": args.gap, "pages": pages}

    out_dir = PUBLIC / series
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "timeline.json").write_text(
        json.dumps(timeline, ensure_ascii=False, indent=2), encoding="utf-8")
    (out_dir / "timeline.ts").write_text(
        'import type { Timeline } from "../../src/types";\n'
        f'import data from "./timeline.json";\n'
        "export const timeline = data as unknown as Timeline;\n",
        encoding="utf-8")

    # 音频软链
    link = PUBLIC / "audio" / series
    if not link.exists():
        link.parent.mkdir(parents=True, exist_ok=True)
        link.symlink_to(audio_dir)

    # 入口（registerRoot 必须字面出现，CLI 静态扫）
    entry = REMOTION / "src" / "series" / f"{series}.tsx"
    entry.parent.mkdir(parents=True, exist_ok=True)
    missing = [p["id"] for p in pages
               if not (PUBLIC / p["board"]).is_file()] if pages else []
    entry.write_text(
        "// GENERATED by scripts/build_from_pack.py - do not edit by hand.\n"
        'import React from "react";\n'
        'import { Composition, registerRoot } from "remotion";\n'
        'import { Lesson, totalFrames } from "../Lesson";\n'
        f'import {{ timeline }} from "../../public/{series}/timeline";\n\n'
        f'const placeholderBoard = {str(bool(missing)).lower()};\n'
        "const compId = \"" + series.replace("_", "-") + "Course\";\n"
        "const Root: React.FC = () => (\n"
        "  <Composition\n"
        "    id={compId}\n"
        "    component={Lesson}\n"
        "    durationInFrames={Math.max(totalFrames(timeline, timeline.fps), 1)}\n"
        "    fps={timeline.fps}\n"
        "    width={timeline.width}\n"
        "    height={timeline.height}\n"
        "    defaultProps={{ timeline, placeholderBoard }}\n"
        "  />\n"
        ");\n\n"
        "registerRoot(Root);\n",
        encoding="utf-8")

    total = sum(p["pageSeconds"] for p in pages)
    print(f"集 {series}: {len(pages)} 页 / {sum(len(p['slots']) for p in pages)} 槽位"
          f" / 总长 {total:.1f}s / 帧数 {round(total * FPS)}")
    if missing:
        print(f"  探针片（板面缺失）：{','.join(missing)}")
    print(f"  -> {out_dir / 'timeline.json'}")
    print(f"  渲染: cd remotion && npx remotion render src/series/{series}.tsx {series.replace('_', '-')}Course out/{series}.mp4 --codec=h264")
    return 0


if __name__ == "__main__":
    sys.exit(main())
